INSERT INTO SHIP_TYPE (NAME, MEAN_SPEED, SPEED_DEVIATION, MEAN_POWER,
POWER_DEVIATION, MEAN_TONNAGE, TONNAGE_DEVIATION)
values('BigShip', 1, 1, 5, 1, 100, 50);

INSERT INTO PORT (X, Y, NAME, OWNER) values(0, 0, 'Port o Prince', 1);
INSERT INTO PORT (X, Y, NAME, OWNER) values(20, 0, 'Britains base', 1);
INSERT INTO PORT (X, Y, NAME, OWNER) values(0, 40, 'Spains base', 2);
INSERT INTO PORT (X, Y, NAME, OWNER) values(20, 40, 'Martinica', 2);
INSERT INTO PORT (X, Y, NAME, OWNER) values(10, 20, 'Cuba', 2);


INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(1, 2, 20, 420);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(1, 3, 40, 1337);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(1, 4, 45, 228);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(1, 5, 22, 332);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(2, 3, 45, 420);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(2, 4, 40, 1488);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(2, 5, 22, 1337);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(3, 4, 40, 420);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(3, 5, 22, 228);

INSERT INTO ROUTE (FROM_PORT, TO_PORT, DISTANCE, REWARD) values(4, 5, 22, 322);
